import { Station, Asset, TrainMovement, BlockRequest, OptimizedSchedule, ScheduleComparison } from '../types';

/**
 * 6 Stations on the Delhi-Agra Corridor
 */
export const STATIONS: Station[] = [
  { id: 'STN_NDLS', code: 'NDLS', name: 'New Delhi', km: 0, platforms: 16, division: 'Delhi', zone: 'Northern Railway' },
  { id: 'STN_GZB', code: 'GZB', name: 'Ghaziabad Junction', km: 30, platforms: 6, division: 'Delhi', zone: 'Northern Railway' },
  { id: 'STN_ALG', code: 'ALG', name: 'Aligarh Junction', km: 120, platforms: 7, division: 'Prayagraj', zone: 'North Central Railway' },
  { id: 'STN_TDK', code: 'TDK', name: 'Tundla Junction', km: 170, platforms: 5, division: 'Prayagraj', zone: 'North Central Railway' },
  { id: 'STN_MTJ', code: 'MTJ', name: 'Mathura Junction', km: 210, platforms: 10, division: 'Agra', zone: 'North Central Railway' },
  { id: 'STN_AGC', code: 'AGC', name: 'Agra Cantt', km: 265, platforms: 6, division: 'Agra', zone: 'North Central Railway' },
];

/**
 * 5 Track Sections connecting the 6 Stations
 */
export const ASSETS: Asset[] = [
  {
    id: 'SEC_NDLS_GZB',
    name: 'New Delhi to Ghaziabad',
    asset_type: 'track_section',
    line: 'Delhi-Agra Corridor',
    zone: 'Northern Railway',
    division: 'Delhi Division',
    start_km: 0,
    end_km: 30,
    max_speed_kmph: 130,
    electrified: true,
    status: 'operational',
  },
  {
    id: 'SEC_GZB_ALG',
    name: 'Ghaziabad to Aligarh',
    asset_type: 'track_section',
    line: 'Delhi-Agra Corridor',
    zone: 'Northern Railway',
    division: 'Delhi Division',
    start_km: 30,
    end_km: 120,
    max_speed_kmph: 130,
    electrified: true,
    status: 'operational',
  },
  {
    id: 'SEC_ALG_TDK',
    name: 'Aligarh to Tundla',
    asset_type: 'track_section',
    line: 'Delhi-Agra Corridor',
    zone: 'North Central Railway',
    division: 'Prayagraj Division',
    start_km: 120,
    end_km: 170,
    max_speed_kmph: 120,
    electrified: true,
    status: 'operational',
  },
  {
    id: 'SEC_TDK_MTJ',
    name: 'Tundla to Mathura',
    asset_type: 'track_section',
    line: 'Delhi-Agra Corridor',
    zone: 'North Central Railway',
    division: 'Agra Division',
    start_km: 170,
    end_km: 210,
    max_speed_kmph: 110,
    electrified: true,
    status: 'operational',
  },
  {
    id: 'SEC_MTJ_AGC',
    name: 'Mathura to Agra Cantt',
    asset_type: 'track_section',
    line: 'Delhi-Agra Corridor',
    zone: 'North Central Railway',
    division: 'Agra Division',
    start_km: 210,
    end_km: 265,
    max_speed_kmph: 110,
    electrified: true,
    status: 'operational',
  },
];

/**
 * 11 Timetabled Trains matching our Python congested scenario
 */
export const CONGESTED_TRAINS: TrainMovement[] = [
  {
    id: 'T01',
    train_number: '12002',
    name: 'Bhopal Shatabdi',
    train_type: 'shatabdi',
    priority: 1,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 360, exit_time: 375 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 395, exit_time: 440 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 460, exit_time: 490 },
      { asset_id: 'SEC_TDK_MTJ', entry_time: 510, exit_time: 535 },
      { asset_id: 'SEC_MTJ_AGC', entry_time: 555, exit_time: 590 },
    ],
  },
  {
    id: 'T02',
    train_number: '12001',
    name: 'NDLS Shatabdi',
    train_type: 'shatabdi',
    priority: 1,
    sections: [
      { asset_id: 'SEC_MTJ_AGC', entry_time: 1050, exit_time: 1085 },
      { asset_id: 'SEC_TDK_MTJ', entry_time: 1105, exit_time: 1130 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 1185, exit_time: 1215 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 1235, exit_time: 1280 },
      { asset_id: 'SEC_NDLS_GZB', entry_time: 1300, exit_time: 1315 },
    ],
  },
  {
    id: 'T03',
    train_number: '12301',
    name: 'Howrah Rajdhani',
    train_type: 'rajdhani',
    priority: 1,
    sections: [
      { asset_id: 'SEC_ALG_TDK', entry_time: 840, exit_time: 865 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 885, exit_time: 925 },
      { asset_id: 'SEC_NDLS_GZB', entry_time: 945, exit_time: 960 },
    ],
  },
  {
    id: 'T04',
    train_number: '14212',
    name: 'Intercity Express',
    train_type: 'express',
    priority: 3,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 1000, exit_time: 1020 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 1040, exit_time: 1100 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 1120, exit_time: 1150 },
    ],
  },
  {
    id: 'T05',
    train_number: '22413',
    name: 'NZM Superfast',
    train_type: 'express',
    priority: 3,
    sections: [
      { asset_id: 'SEC_TDK_MTJ', entry_time: 600, exit_time: 630 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 650, exit_time: 685 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 705, exit_time: 770 },
    ],
  },
  {
    id: 'T06',
    train_number: '58001',
    name: 'Freight BCNA Rake',
    train_type: 'freight',
    priority: 8,
    sections: [
      { asset_id: 'SEC_GZB_ALG', entry_time: 60, exit_time: 160 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 180, exit_time: 250 },
    ],
  },
  {
    id: 'T07',
    train_number: '58002',
    name: 'Freight Container',
    train_type: 'freight',
    priority: 8,
    sections: [
      { asset_id: 'SEC_TDK_MTJ', entry_time: 120, exit_time: 180 },
      { asset_id: 'SEC_MTJ_AGC', entry_time: 200, exit_time: 270 },
    ],
  },
  {
    id: 'T08',
    train_number: '58003',
    name: 'Freight Tanker',
    train_type: 'freight',
    priority: 8,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 1350, exit_time: 1380 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 1395, exit_time: 1435 },
    ],
  },
  {
    id: 'T09',
    train_number: '20172',
    name: 'Vande Bharat Express',
    train_type: 'superfast',
    priority: 1,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 480, exit_time: 495 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 515, exit_time: 555 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 575, exit_time: 605 },
      { asset_id: 'SEC_TDK_MTJ', entry_time: 665, exit_time: 690 },
      { asset_id: 'SEC_MTJ_AGC', entry_time: 710, exit_time: 745 },
    ],
  },
  {
    id: 'T10',
    train_number: '12280',
    name: 'Taj Express',
    train_type: 'superfast',
    priority: 2,
    sections: [
      { asset_id: 'SEC_MTJ_AGC', entry_time: 880, exit_time: 915 },
      { asset_id: 'SEC_TDK_MTJ', entry_time: 1010, exit_time: 1035 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 1060, exit_time: 1090 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 1145, exit_time: 1190 },
      { asset_id: 'SEC_NDLS_GZB', entry_time: 1210, exit_time: 1225 },
    ],
  },
  {
    id: 'T11',
    train_number: '12050',
    name: 'Gatimaan Express',
    train_type: 'superfast',
    priority: 1,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 720, exit_time: 735 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 810, exit_time: 850 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 900, exit_time: 925 },
      { asset_id: 'SEC_TDK_MTJ', entry_time: 945, exit_time: 970 },
      { asset_id: 'SEC_MTJ_AGC', entry_time: 980, exit_time: 1015 },
    ],
  },
];

/**
 * 8 Standard Demo Trains (Synthetic Delhi-Agra baseline)
 */
export const STANDARD_TRAINS: TrainMovement[] = [
  {
    id: 'T1',
    train_number: '12002',
    name: 'Bhopal Shatabdi',
    train_type: 'shatabdi',
    priority: 1,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 360, exit_time: 375 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 395, exit_time: 440 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 460, exit_time: 490 },
      { asset_id: 'SEC_TDK_MTJ', entry_time: 510, exit_time: 535 },
      { asset_id: 'SEC_MTJ_AGC', entry_time: 555, exit_time: 590 },
    ],
  },
  {
    id: 'T2',
    train_number: '12001',
    name: 'NDLS Shatabdi',
    train_type: 'shatabdi',
    priority: 1,
    sections: [
      { asset_id: 'SEC_MTJ_AGC', entry_time: 1050, exit_time: 1085 },
      { asset_id: 'SEC_TDK_MTJ', entry_time: 1105, exit_time: 1130 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 1185, exit_time: 1215 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 1235, exit_time: 1280 },
      { asset_id: 'SEC_NDLS_GZB', entry_time: 1300, exit_time: 1315 },
    ],
  },
  {
    id: 'T3',
    train_number: '12301',
    name: 'Howrah Rajdhani',
    train_type: 'rajdhani',
    priority: 1,
    sections: [
      { asset_id: 'SEC_ALG_TDK', entry_time: 840, exit_time: 865 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 885, exit_time: 925 },
      { asset_id: 'SEC_NDLS_GZB', entry_time: 945, exit_time: 960 },
    ],
  },
  {
    id: 'T4',
    train_number: '14212',
    name: 'Intercity Express',
    train_type: 'express',
    priority: 3,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 1000, exit_time: 1020 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 1040, exit_time: 1100 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 1120, exit_time: 1150 },
    ],
  },
  {
    id: 'T5',
    train_number: '22413',
    name: 'NZM Superfast',
    train_type: 'express',
    priority: 3,
    sections: [
      { asset_id: 'SEC_TDK_MTJ', entry_time: 600, exit_time: 630 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 650, exit_time: 685 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 705, exit_time: 770 },
    ],
  },
  {
    id: 'T6',
    train_number: '58001',
    name: 'Freight BCNA Rake',
    train_type: 'freight',
    priority: 8,
    sections: [
      { asset_id: 'SEC_GZB_ALG', entry_time: 60, exit_time: 160 },
      { asset_id: 'SEC_ALG_TDK', entry_time: 180, exit_time: 250 },
    ],
  },
  {
    id: 'T7',
    train_number: '58002',
    name: 'Freight Container',
    train_type: 'freight',
    priority: 8,
    sections: [
      { asset_id: 'SEC_TDK_MTJ', entry_time: 120, exit_time: 180 },
      { asset_id: 'SEC_MTJ_AGC', entry_time: 200, exit_time: 270 },
    ],
  },
  {
    id: 'T8',
    train_number: '58003',
    name: 'Freight Tanker',
    train_type: 'freight',
    priority: 8,
    sections: [
      { asset_id: 'SEC_NDLS_GZB', entry_time: 1350, exit_time: 1380 },
      { asset_id: 'SEC_GZB_ALG', entry_time: 1395, exit_time: 1435 },
    ],
  },
];

/**
 * 8 Standard Demo Maintenance Blocks
 */
export const STANDARD_BLOCKS: BlockRequest[] = [
  {
    id: 'BR_001',
    asset_id: 'SEC_GZB_ALG',
    maintenance_type: 'emergency_repair',
    priority: 4,
    duration_minutes: 90,
    earliest_start: 60,
    latest_end: 350,
    preferred_start: 180,
    requested_by: 'Track Engineering',
    crew_required: 2,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_002',
    asset_id: 'SEC_ALG_TDK',
    maintenance_type: 'track_renewal',
    priority: 3,
    duration_minutes: 120,
    earliest_start: 270,
    latest_end: 830,
    preferred_start: 500,
    requested_by: 'Civil Engineering',
    crew_required: 2,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_003',
    asset_id: 'SEC_NDLS_GZB',
    maintenance_type: 'ohe_maintenance',
    priority: 3,
    duration_minutes: 120,
    earliest_start: 60,
    latest_end: 340,
    preferred_start: 120,
    requested_by: 'Electrical TRD',
    crew_required: 1,
    requires_power_block: true,
    status: 'pending',
  },
  {
    id: 'BR_004',
    asset_id: 'SEC_TDK_MTJ',
    maintenance_type: 'routine_inspection',
    priority: 2,
    duration_minutes: 90,
    earliest_start: 240,
    latest_end: 580,
    preferred_start: 400,
    requested_by: 'Permanent Way',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_005',
    asset_id: 'SEC_MTJ_AGC',
    maintenance_type: 'rail_grinding',
    priority: 2,
    duration_minutes: 180,
    earliest_start: 300,
    latest_end: 1040,
    preferred_start: 600,
    requested_by: 'Track Machines',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_006',
    asset_id: 'SEC_GZB_ALG',
    maintenance_type: 'bridge_inspection',
    priority: 1,
    duration_minutes: 60,
    earliest_start: 780,
    latest_end: 1190,
    preferred_start: 880,
    requested_by: 'Bridge Wing',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_007',
    asset_id: 'SEC_ALG_TDK',
    maintenance_type: 'signal_maintenance',
    priority: 5,
    duration_minutes: 45,
    earliest_start: 700,
    latest_end: 835,
    preferred_start: 720,
    requested_by: 'Signaling Dept',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_008',
    asset_id: 'SEC_NDLS_GZB',
    maintenance_type: 'routine_inspection',
    priority: 2,
    duration_minutes: 60,
    earliest_start: 1100,
    latest_end: 1340,
    preferred_start: 1200,
    requested_by: 'Track Inspection',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
];

/**
 * 10 Congested Maintenance Block Requests
 */
export const CONGESTED_BLOCKS: BlockRequest[] = [
  {
    id: 'BR_C01',
    asset_id: 'SEC_GZB_ALG',
    maintenance_type: 'emergency_repair',
    priority: 5,
    duration_minutes: 90,
    earliest_start: 270,
    latest_end: 550,
    preferred_start: 390,
    requested_by: 'Track Safety Division',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_C02',
    asset_id: 'SEC_GZB_ALG',
    maintenance_type: 'track_renewal',
    priority: 3,
    duration_minutes: 150,
    earliest_start: 450,
    latest_end: 720,
    preferred_start: 480,
    requested_by: 'Civil Engineering',
    crew_required: 2,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_C03',
    asset_id: 'SEC_NDLS_GZB',
    maintenance_type: 'ohe_maintenance',
    priority: 4,
    duration_minutes: 120,
    earliest_start: 450,
    latest_end: 700,
    preferred_start: 480,
    requested_by: 'Electrical TRD',
    crew_required: 1,
    requires_power_block: true,
    status: 'pending',
  },
  {
    id: 'BR_C04',
    asset_id: 'SEC_NDLS_GZB',
    maintenance_type: 'signal_maintenance',
    priority: 3,
    duration_minutes: 90,
    earliest_start: 450,
    latest_end: 680,
    preferred_start: 500,
    requested_by: 'Signaling & Telecom',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_C05',
    asset_id: 'SEC_ALG_TDK',
    maintenance_type: 'routine_inspection',
    priority: 2,
    duration_minutes: 90,
    earliest_start: 800,
    latest_end: 1050,
    preferred_start: 840,
    requested_by: 'Track Inspection Wing',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_C06',
    asset_id: 'SEC_ALG_TDK',
    maintenance_type: 'ballast_cleaning',
    priority: 1,
    duration_minutes: 90,
    earliest_start: 800,
    latest_end: 1020,
    preferred_start: 880,
    requested_by: 'Track Machines',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_C07',
    asset_id: 'SEC_TDK_MTJ',
    maintenance_type: 'signal_maintenance',
    priority: 3,
    duration_minutes: 120,
    earliest_start: 640,
    latest_end: 920,
    preferred_start: 660,
    requested_by: 'Signaling & Telecom',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_C08',
    asset_id: 'SEC_TDK_MTJ',
    maintenance_type: 'bridge_inspection',
    priority: 2,
    duration_minutes: 90,
    earliest_start: 680,
    latest_end: 930,
    preferred_start: 700,
    requested_by: 'Bridge Engineering',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
  {
    id: 'BR_C09',
    asset_id: 'SEC_MTJ_AGC',
    maintenance_type: 'ohe_maintenance',
    priority: 4,
    duration_minutes: 90,
    earliest_start: 500,
    latest_end: 700,
    preferred_start: 550,
    requested_by: 'Electrical TRD',
    crew_required: 1,
    requires_power_block: true,
    status: 'pending',
  },
  {
    id: 'BR_C10',
    asset_id: 'SEC_MTJ_AGC',
    maintenance_type: 'routine_inspection',
    priority: 1,
    duration_minutes: 90,
    earliest_start: 900,
    latest_end: 1150,
    preferred_start: 980,
    requested_by: 'Permanent Way',
    crew_required: 1,
    requires_power_block: false,
    status: 'pending',
  },
];

/**
 * Precomputed Optimal Schedule from CP-SAT for Congested Scenario
 * Used as immediate demo display before on-demand CP-SAT solver re-execution.
 */
export const INITIAL_SCHEDULE: OptimizedSchedule = {
  id: 'schedule_delhi_agra_optimal',
  name: 'Optimized Maintenance Block Schedule (Delhi–Agra Corridor)',
  planning_horizon_minutes: 1440,
  created_at: new Date().toISOString(),
  solver_config: {
    max_solve_time_seconds: 30,
    safety_buffer_minutes: 15,
    num_workers: 8,
    priority_weight_multiplier: 10000,
    deviation_penalty_weight: 10,
    disclaimer: 'Safety buffer and weights are demo assumptions, not official Indian Railways parameters.',
  },
  metrics: {
    total_blocks_requested: 10,
    total_blocks_scheduled: 6,
    total_blocks_skipped: 4,
    objective_score: 195750.0,
    total_affected_trains: 0,
    total_deviation_minutes: 425,
    average_deviation_minutes: 70.83,
    asset_utilization_percent: 8.33,
    solve_time_seconds: 0.0069,
    solver_status: 'OPTIMAL',
    train_conflicts: 0,
    estimated_train_delay_minutes: 0,
    resource_conflicts: 0,
    total_asset_downtime_minutes: 600,
  },
  warnings: [],
  demo_disclaimer: 'This schedule was generated using synthetic demo data and is not based on real Indian Railways operations.',
  blocks: [
    {
      block_request_id: 'BR_C01',
      asset_id: 'SEC_GZB_ALG',
      asset_name: 'Ghaziabad to Aligarh',
      maintenance_type: 'emergency_repair',
      priority: 5,
      scheduled_start: 290,
      scheduled_end: 380,
      duration_minutes: 90,
      preferred_start: 390,
      deviation_minutes: 100,
      affected_trains: [],
      is_scheduled: true,
    },
    {
      block_request_id: 'BR_C02',
      asset_id: 'SEC_GZB_ALG',
      asset_name: 'Ghaziabad to Aligarh',
      maintenance_type: 'track_renewal',
      priority: 3,
      scheduled_start: -1,
      scheduled_end: -1,
      duration_minutes: 150,
      preferred_start: 480,
      deviation_minutes: 0,
      affected_trains: [],
      is_scheduled: false,
      skip_reason: 'Deferred by CP-SAT: High-priority track section occupied by Emergency Repair BR_C01 and Vande Bharat Express',
    },
    {
      block_request_id: 'BR_C03',
      asset_id: 'SEC_NDLS_GZB',
      asset_name: 'New Delhi to Ghaziabad',
      maintenance_type: 'ohe_maintenance',
      priority: 4,
      scheduled_start: 510,
      scheduled_end: 630,
      duration_minutes: 120,
      preferred_start: 480,
      deviation_minutes: 30,
      affected_trains: [],
      is_scheduled: true,
    },
    {
      block_request_id: 'BR_C04',
      asset_id: 'SEC_NDLS_GZB',
      asset_name: 'New Delhi to Ghaziabad',
      maintenance_type: 'signal_maintenance',
      priority: 3,
      scheduled_start: -1,
      scheduled_end: -1,
      duration_minutes: 90,
      preferred_start: 500,
      deviation_minutes: 0,
      affected_trains: [],
      is_scheduled: false,
      skip_reason: 'Deferred by CP-SAT: Section NDLS-GZB occupied by OHE Maintenance BR_C03 and Vande Bharat/Gatimaan paths',
    },
    {
      block_request_id: 'BR_C05',
      asset_id: 'SEC_ALG_TDK',
      asset_name: 'Aligarh to Tundla',
      maintenance_type: 'routine_inspection',
      priority: 2,
      scheduled_start: 940,
      scheduled_end: 1030,
      duration_minutes: 90,
      preferred_start: 840,
      deviation_minutes: 100,
      affected_trains: [],
      is_scheduled: true,
    },
    {
      block_request_id: 'BR_C06',
      asset_id: 'SEC_ALG_TDK',
      asset_name: 'Aligarh to Tundla',
      maintenance_type: 'ballast_cleaning',
      priority: 1,
      scheduled_start: -1,
      scheduled_end: -1,
      duration_minutes: 90,
      preferred_start: 880,
      deviation_minutes: 0,
      affected_trains: [],
      is_scheduled: false,
      skip_reason: 'Deferred by CP-SAT: Low-priority request skipped to preserve crew capacity and avoid Howrah Rajdhani conflict',
    },
    {
      block_request_id: 'BR_C07',
      asset_id: 'SEC_TDK_MTJ',
      asset_name: 'Tundla to Mathura',
      maintenance_type: 'signal_maintenance',
      priority: 3,
      scheduled_start: 795,
      scheduled_end: 915,
      duration_minutes: 120,
      preferred_start: 660,
      deviation_minutes: 135,
      affected_trains: [],
      is_scheduled: true,
    },
    {
      block_request_id: 'BR_C08',
      asset_id: 'SEC_TDK_MTJ',
      asset_name: 'Tundla to Mathura',
      maintenance_type: 'bridge_inspection',
      priority: 2,
      scheduled_start: 705,
      scheduled_end: 795,
      duration_minutes: 90,
      preferred_start: 700,
      deviation_minutes: 5,
      affected_trains: [],
      is_scheduled: true,
    },
    {
      block_request_id: 'BR_C09',
      asset_id: 'SEC_MTJ_AGC',
      asset_name: 'Mathura to Agra Cantt',
      maintenance_type: 'ohe_maintenance',
      priority: 4,
      scheduled_start: 605,
      scheduled_end: 695,
      duration_minutes: 90,
      preferred_start: 550,
      deviation_minutes: 55,
      affected_trains: [],
      is_scheduled: true,
    },
    {
      block_request_id: 'BR_C10',
      asset_id: 'SEC_MTJ_AGC',
      asset_name: 'Mathura to Agra Cantt',
      maintenance_type: 'routine_inspection',
      priority: 1,
      scheduled_start: -1,
      scheduled_end: -1,
      duration_minutes: 90,
      preferred_start: 980,
      deviation_minutes: 0,
      affected_trains: [],
      is_scheduled: false,
      skip_reason: 'Deferred by CP-SAT: Priority 1 deferred to ensure punctuality of Gatimaan Express corridor path',
    },
  ],
};

/**
 * Precomputed Comparison Benchmark (Naive vs CP-SAT)
 */
export const INITIAL_COMPARISON: ScheduleComparison = {
  scenario_name: 'Delhi-Agra Congested Corridor Benchmark',
  planning_horizon_minutes: 1440,
  naive_plan: {
    scheduler_type: 'Naive Baseline (Preferred Times)',
    blocks_requested: 10,
    blocks_scheduled: 10,
    blocks_skipped: 0,
    train_conflicts: 12,
    estimated_train_delay_minutes: 1235,
    affected_trains_count: 5,
    affected_trains: [
      '12002 (Bhopal Shatabdi)',
      '12952 (Mumbai Rajdhani)',
      '12301 (Howrah Rajdhani)',
      '20172 (Vande Bharat Express)',
      '12050 (Gatimaan Express)',
    ],
    total_deviation_minutes: 0,
    average_deviation_minutes: 0.0,
    asset_downtime_minutes: 1020,
    asset_utilization_percent: 14.17,
    resource_conflicts: 1,
    max_crews_demanded: 5,
    crew_capacity: 2,
    objective_score: -96750,
    solver_status: 'UNOPTIMIZED',
    runtime_seconds: 0.0002,
  },
  optimized_plan: {
    scheduler_type: 'Google OR-Tools CP-SAT',
    blocks_requested: 10,
    blocks_scheduled: 6,
    blocks_skipped: 4,
    train_conflicts: 0,
    estimated_train_delay_minutes: 0,
    affected_trains_count: 0,
    affected_trains: [],
    total_deviation_minutes: 425,
    average_deviation_minutes: 70.83,
    asset_downtime_minutes: 600,
    asset_utilization_percent: 8.33,
    resource_conflicts: 0,
    max_crews_demanded: 2,
    crew_capacity: 2,
    objective_score: 195750.0,
    solver_status: 'OPTIMAL',
    runtime_seconds: 0.0069,
  },
  improvement_summary: {
    train_conflicts_eliminated: 12,
    train_conflicts_reduction_percent: 100.0,
    train_delay_saved_minutes: 1235,
    train_delay_reduction_percent: 100.0,
    resource_conflicts_resolved: 1,
    objective_score_delta: 292500,
    safety_compliance: 'COMPLIANT_ZERO_CONFLICTS',
  },
  demo_disclaimer: 'This benchmark comparison was generated using synthetic demo data and is not based on real Indian Railways operations.',
};
